<?xml version="1.0" encoding="utf-8"?><Database Name="EldersDB" Class="EldersDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=EldersDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EldersDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Seniors" Member="Seniors">
    <Type Name="Senior">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="YearOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Seniority" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>